app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Home
Route::get('/', 'HomeController@index')->name('home');

// Invoice CRUD
Route::resource('/invoice', 'InvoiceController');
Route::get('/invoice/date/{id}', 'InvoiceController@dates')->name('invoice.dates');
Route::put('/invoice/date/{id}', 'InvoiceController@datesUpdate')->name('invoice.datesUpdate');

// Authentication routes
Route::get('login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('logout', 'Auth\AuthController@getLogout')->name('auth.logout');

// Password reset link request routes.
Route::get('password/email', 'Auth\PasswordController@getEmail')->name('password.email');
Route::post('password/email', 'Auth\PasswordController@postEmail')->name('password.email');

// Password reset routes
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

// Vessels routes
Route::resource('vessel', 'VesselController');

// RDAs routes
Route::resource('rda', 'RdaController');

// Agencies routes
Route::resource('agency', 'AgencyController');

// Ports routes
Route::resource('port', 'PortController');
Route::get('port/data/{id}','PortController@data')->name('port.data');

// Employers routes
Route::resource('employer', 'EmployerController');

// Vehicles routes
Route::resource('vehicle', 'VehicleController');

// Users routes
Route::resource('user', 'UserController');

// Approval routes
Route::resource('approval', 'ApprovalController');
Route::get('approval/line-up/{id}', 'ApprovalController@lineUp')->name('approval.lineUp');
Route::get('approval/billing/{id}', 'ApprovalController@billing')->name('approval.billing');

// Billing routes
Route::resource('billing', 'BillingController');

// Historic routes
Route::resource('historic', 'HistoricController');

// Settlement routes
Route::get('settlement/all', 'SettlementController@all')->name('settlement.all');
Route::get('settlement/not-supplied', 'SettlementController@notSupplied')->name('settlement.notSupplied');
Route::get('settlement/supplied', 'SettlementController@supplied')->name('settlement.supplied');

// Report routes
Route::get('report', 'ReportController@index')->name('report');

// Operational list routes
Route::get('programacao', 'OperationalController@index')->name('operational');

resources/views/footer.blade.php
<footer class="footer">
    <div class="container">
        <p class="text-muted text-center">
            <span class="white">SGCVS - Sistema de Gestão Comercial Vitória Ship. Desenvolvido por Popify. Versão 1.0.</span>
            <br>Reporte problemas tiago@tcosta.com.br ou (27) 99273-5492.
        </p>
    </div>
</footer>

resources/views/main.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex" />
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <link rel="icon" href="/assets/images/favicon.ico">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
        <title>@yield('title')</title>
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="/assets/css/bootstrap.css">
        <link rel="stylesheet" href="/assets/css/jquery-ui-1.10.0.custom.css" />
        <link rel="stylesheet" href="/assets/css/font-awesome.min.css" />
        <link rel="stylesheet" href="/assets/css/ie10-viewport-bug-workaround.css">
        <link rel="stylesheet" href="/assets/js/fancy/jquery.fancybox.css"/>
        <link rel="stylesheet" href="/assets/css/style.css">
        <!-- <link href="/media/css/jquery.dataTables.min.css"/> -->
        <link rel="stylesheet" href="/media/css/dataTables.bootstrap.min.css"/>
        <link rel="stylesheet" href="/media/css/buttons.bootstrap.min.css"/>
        <link rel="stylesheet" href="/media/css/buttons.dataTables.min.css"/>
        <link rel="stylesheet" href="/assets/css/sweetalert.css"/>
        <!--[if IE 7]>
        <link rel="stylesheet" href="/assets/css/font-awesome-ie7.min.css">
        <![endif]-->
        <!--[if lt IE 9]>
        <link rel="stylesheet" type="text/css" href="/assets/css/jquery.ui.1.10.0.ie.css"/>
        <![endif]-->
    </head>
    <body>

        <div class="loader"></div>

        @yield('navbar')

        @yield('content')

        @include('scripts')

    </body>
</html>

resources/views/messages.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>We found some errors.</strong>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if($status)
    <div class="alert alert-info alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ $status }}
    </div>
@endif

resources/views/navbar.blade.php
@if(Auth::user()->group->id != 4)
<nav class="navbar navbar-default navbar-fixed-top mod-nav">
    <div class="container-fluid bemvindo">
        <div class="col-xs-6">
            <span class="align-left">
                Welcome
                <strong>{{ Auth::user()->name }}</strong>
            </span>
        </div>
        <div class="col-xs-6">
            <span class="align-right">
                <a class="loading" href="{{ route('auth.logout') }}">
                    <span class="glyphicon glyphicon-log-out"></span> Logout
                </a>
            </span>
        </div>
    </div>
    <div class="container p-t1">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="loading" href="{{ route('home') }}" class="navbar-brand pad0">
                <img class="img-responsive" src="/assets/images/logo.png" alt="Home">
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right mod-nav-r">
                <li>
                    <a class="loading" href="{{ route('home') }}">
                        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                        Line-up
                    </a>
                </li>
                @can('approval')
                <li>
                    <a class="loading" href="{{ route('approval.index') }}">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        Approvals
                    </a>
                </li>
                @endcan
                @can('billing')
                <li>
                    <a class="loading" href="{{ route('billing.index') }}">
                        <span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
                        Billing
                    </a>
                </li>
                @endcan



                @can('settlement')
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Settlement
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="loading" href="{{ route('settlement.all') }}">ALL</a>
                        </li>
                        <li>
                            <a class="loading" href="{{ route('settlement.supplied') }}">SUPPLIED</a>
                        </li>
                        <li>
                            <a class="loading" href="{{ route('settlement.notSupplied') }}">NOT SUPPLIED</a>
                        </li>
                    </ul>
                </li>
                @endcan


                @can('historic')
                <li>
                    <a class="loading" href="{{ route('historic.index') }}">
                        <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
                        Historic
                    </a>
                </li>
                @endcan
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span> Records
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        @can('vessel')
                        <li>
                            <a class="loading" href="{{ route('vessel.index') }}">VESSEL</a>
                        </li>
                        @endcan
                        @can('rda')
                        <li>
                            <a class="loading" href="{{ route('rda.index') }}">R.D.A / CO-R.D.A</a>
                        </li>
                        @endcan
                        @can('agency')
                        <li>
                            <a class="loading" href="{{ route('agency.index') }}">AGENCY</a>
                        </li>
                        @endcan
                        @can('port')
                        <li>
                            <a class="loading" href="{{ route('port.index') }}">PORT</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        @endcan
                        @can('employer')
                        <li>
                            <a class="loading" href="{{ route('employer.index') }}">EMPLOYER</a>
                        </li>
                        @endcan
                        @can('vehicle')
                        <li>
                            <a class="loading" href="{{ route('vehicle.index') }}">VEHICLES</a>
                        </li>
                        @endcan
                        @can('user')
                        <li role="separator" class="divider"></li>
                        <li>
                            <a class="loading" href="{{ route('user.index') }}">USERS</a>
                        </li>
                        @endcan
                    </ul>
                </li>
                @can('report')
                <li class="bar-vert"><a class="loading" href="{{ route('report') }}"><span class="glyphicon glyphicon-copy" aria-hidden="true"></span> Report</a></li>
                @endcan
                @can('create-invoice')
                <li><a href="{{ route('invoice.create') }}" class="novo loading"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> New</a></li>
                @endcan
            </ul>
        </div>
    </div>
</nav>
@endif
<div class="container-fluid bg-sgcvs">
    <div class="container">
        <div class="col-sm-6 col-xs-12">
            @yield('module')
        </div>
        <div class="col-xs-6 hidden-xs">
            <h3 class="text-right white">{{ Auth::user()->locale->name }} <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></h3>
        </div>
    </div>
</div>

resources/views/scripts.blade.php
<!-- Bootstrap core JavaScript # scripts #-->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/jquery-ui-1.10.0.custom.min.js"></script>
<script src="/assets/js/jquery.mask.js"></script>
<script src="/assets/js/fancy/jquery.fancybox.js"></script>
<script src="/assets/js/sweetalert.min.js"></script>
<script src="/media/js/jquery.dataTables.min.js"></script>
<script src="/media/js/moment.min.js"></script>
<script src="/media/js/datetime-moment.js"></script>
<script src="/media/js/dataTables.bootstrap.min.js"></script>
<script src="/media/js/dataTables.buttons.min.js"></script>
<script src="/assets/js/jszip.min.js"></script>
<script src="/assets/js/pdfmake.min.js"></script>
<script src="/assets/js/vfs_fonts.js"></script>
<script src="/media/js/buttons.html5.min.js"></script>
<script src="/media/js/buttons.print.min.js"></script>
<script src="/assets/js/buttons.colVis.min.js"></script>
<script src="/assets/js/jquery.maskMoney.min.js"></script>
<script src="/assets/js/vue.min.js"></script>
<script src="/assets/js/alerts.js"></script>
<script src="/assets/js/vue-app.js"></script>
<script src="/assets/js/SGCVS.js"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/assets/js/ie10-viewport-bug-workaround.js"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->