app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Home
Route::get('/', 'HomeController@index')->name('home');

// Invoice CRUD
Route::resource('/invoice', 'InvoiceController');
Route::get('/invoice/date/{id}', 'InvoiceController@dates')->name('invoice.dates');
Route::put('/invoice/date/{id}', 'InvoiceController@datesUpdate')->name('invoice.datesUpdate');

// Authentication routes
Route::get('login', 'Auth\AuthController@getLogin')->name('auth.login');
Route::post('login', 'Auth\AuthController@postLogin')->name('auth.login');
Route::get('logout', 'Auth\AuthController@getLogout')->name('auth.logout');

// Password reset link request routes.
Route::get('password/email', 'Auth\PasswordController@getEmail')->name('password.email');
Route::post('password/email', 'Auth\PasswordController@postEmail')->name('password.email');

// Password reset routes
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

// Vessels routes
Route::resource('vessel', 'VesselController');

// RDAs routes
Route::resource('rda', 'RdaController');

// Agencies routes
Route::resource('agency', 'AgencyController');

// Ports routes
Route::resource('port', 'PortController');
Route::get('port/data/{id}','PortController@data')->name('port.data');

// Employers routes
Route::resource('employer', 'EmployerController');

// Vehicles routes
Route::resource('vehicle', 'VehicleController');

// Users routes
Route::resource('user', 'UserController');

// Approval routes
Route::resource('approval', 'ApprovalController');
Route::get('approval/line-up/{id}', 'ApprovalController@lineUp')->name('approval.lineUp');
Route::get('approval/billing/{id}', 'ApprovalController@billing')->name('approval.billing');

// Billing routes
Route::resource('billing', 'BillingController');

// Historic routes
Route::resource('historic', 'HistoricController');

// Settlement routes
Route::get('settlement/all', 'SettlementController@all')->name('settlement.all');
Route::get('settlement/not-supplied', 'SettlementController@notSupplied')->name('settlement.notSupplied');
Route::get('settlement/supplied', 'SettlementController@supplied')->name('settlement.supplied');

// Report routes
Route::get('report', 'ReportController@index')->name('report');

// Operational list routes
Route::get('programacao', 'OperationalController@index')->name('operational');

app/Models/Rda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rda extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'type'];

    /**
     * Relationship with Invoice Model
     */
    public function invoice()
    {
        return $this->hasMany('App\Models\Invoice');
    }

    /**
     * Only user of group 1 and 2 can see the RDA/cord
     * name, another ones just see "SIGN" or "COB"
     */
    public function getNameAttribute($value)
    {
        if (in_array(auth()->user()->group->id, [1, 2]))
        {
            return $value;
        }

        return $this->attributes['type'] == 1 ? 'SIGN' : 'COB';
    }

    /**
     * Set value to uppercase
     */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtoupper($value);
    }

    public function setEmailAttribute($value)
    {
        $this->attributes['email'] = strtolower($value);
    }
}

app/Http/Controllers/RdaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Rda;
use Gate;

class RdaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rdas = Rda::all();

        return view('rda.index')->with('rdas', $rdas);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\Rda\StoreRdaRequest $request)
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rda = new Rda;

        $rda->create($request->all());

        return redirect(route('rda.index'))->with('status', 'Rda saved with success.');;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rda = Rda::findOrFail($id);

        return view('rda.edit')->with('rda', $rda);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\Rda\StoreRdaRequest $request, $id)
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rda = Rda::findOrFail($id);

        $rda->fill($request->all())->save();

        return redirect()->back()->with('status', 'RDA/CO-RDA updated with success.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\Rda\DeleteRdaRequest $request, $id)
    {
        if (Gate::denies('rda')) {
            return redirect(route('home'));
        }

        $rda = Rda::findOrFail($id);

        $rda->delete();

        return redirect()->back()->with('status', 'RDA/CO-RDA deleted with success.');
    }
}

resources/views/rda/edit.blade.php
@extends('main')

@section('title', 'Edit RDA/CO-RDA')

@section('content')

<div class="container p-t1">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row form-horizontal">
            <form action="{{ route('rda.update', $rda->id) }}" method="post">
                {!! csrf_field() !!}
                <input name="_method" type="hidden" value="PUT">
                <div class="col-sm-5">
                    @include('messages')
                    <div class="col-sm-4">
                        <div class="form-group row">
                            <label for="nome_rda" class="col-sm-4 control-label">
                                <span class= "red">*</span> Name
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="name" value="{{ $rda->name }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="email_rda" class="col-sm-5 control-label">
                                <span class= "red">*</span> E-mail
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="email" value="{{ $rda->email }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 p-t4">
                        <div class="form-group row">
                            <label for="tipo_rda" class="col-sm-5 control-label">
                                <span class= "red">*</span> Type
                            </label>
                            <div class="col-sm-7">
                                <select name="type" class="form-control">
                                    <option value="1" {{ ($rda->type == 1 ? "selected":"") }}>SIGN</option>
                                    <option value="0" {{ ($rda->type == 0 ? "selected":"") }}>COB</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <input class="btn btn-primary loading" type="submit" value="SAVE" >
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>

<script type="text/javascript">document.getElementsByTagName('body')[0].className+='nopad'</script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="assets/js/ie10-viewport-bug-workaround.js"></script>

@endsection

resources/views/rda/index.blade.php
@extends('main')

@section('title', 'RDA/CO-RDA | SGCVS - Sistema de Gestão Comercial Vitória Ship')

@section('navbar')

    @section('module')
        <h3 class="white">
            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true">
            </span> Records <span class="font-l">/ R.D.A e CO-R.D.A</span>
        </h3>
    @endsection

    @include('navbar')

@endsection

@section('content')

    <div class="container p-t1">
        @include('messages')
        <div class="panel panel-default">
            <form action="{{ route('rda.store') }}" method="post">
            {!! csrf_field() !!}
            <div class="panel-body p-t7">
                <div class="row form-horizontal">
                    <div class="col-sm-4">
                        <div class="form-group row">
                            <label for="nome_rda" class="col-sm-4 control-label">
                                <span class= "red">*</span> Name
                            </label>
                            <div class="col-sm-8">
                                <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 p-t4">
                        <div class="form-group row">
                            <label for="email_rda" class="col-sm-3 control-label">
                                <span class="red">*</span> E-mail
                            </label>
                            <div class="col-sm-9">
                                <input type="email" name="email" class="form-control" value="{{ old('email') }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2 p-t4">
                        <div class="form-group row">
                            <label for="tem_estiva" class="col-sm-5 control-label">
                                <span class= "red">*</span> Type
                            </label>
                            <div class="col-sm-7">
                                <select name="type" class="form-control">
                                    <option value="1">SIGN</option>
                                    <option value="0">COB</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <input class="btn btn-primary btn-block loading" type="submit" value="SAVE" >
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
    <div class="container">
        <div class="table-responsive">
            <table class="table table-bordered table-condensed table-hover data-table">
                <thead>
                    <tr class="active">
                        <th>Name</th>
                        <th>E-mail</th>
                        <th>Type</th>
                        <th class="opcoes">Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($rdas as $rda)
                    <tr>
                        <td>{{ $rda->name }}</td>
                        <td>{{ $rda->email }}</td>
                        <td>{{ ($rda->type == 1 ? "SIGN":"COB") }}</td>
                        <td>
                            <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                <div class="btn-group btn-group-xs" role="group">
                                    <a href="{{ route('rda.edit', $rda->id) }}" class="btn btn-default iframe fancybox.iframe border-right-n">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                </div>
                                <div class="btn-group btn-group-xs" role="group">
                                    <a href="{{ route('rda.destroy', $rda->id) }}" class="btn btn-default"
                                        data-token="{{ csrf_token() }}"
                                        data-delete=""
                                        data-title="Are you sure?"
                                        data-message="Are you sure that you want delete {{ $rda->name }}?"
                                        data-button-text="Yes, delete it!">
                                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@include('footer')

@endsection